### PR TITLE
Simplify testing

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
These failures are from non-related and pre-existing rubocop issues.

**Comment by rnelson0** [comment]
Wouldn't strict still need enabled for 3.x?

**Comment by ghoneycutt** [comment]
Good eye, you're quite right. I'll rebase.

**Comment by bastelfreak** [comment]
We manage both files with our modulesync. @ghoneycutt could you provide the patch instead to https://github.com/voxpupuli/modulesync_config/blob/master/config_defaults.yml ?

**Comment by rnelson0** [comment]
Might be good to make sure it passes here before closing it out, to reduce the number of module syncs required.

**Comment by ghoneycutt** [comment]
@bastelfreak Sent a PR for the STRICT_VARIABLES https://github.com/voxpupuli/modulesync_config/pull/216

Not sure how the commit to the Rakefile in this PR can be used in the modulesync_config repo.

**Comment by bastelfreak** [comment]
`.travis.yml` and 'Gemfile` should now be updated in our modulesync_config. `Rakefile` is still on the list.  This got recently merged but not yet applied to any module:
https://github.com/voxpupuli/modulesync_config/pull/210

I didn't have the time yet to compare all the different tasks and which we want and which not.

**Comment by alexjfisher** [comment]
Closing as https://github.com/voxpupuli/modulesync_config/pull/216 and https://github.com/voxpupuli/modulesync_config/pull/210 were merged and used in https://github.com/voxpupuli/puppet-archive/pull/207

Thanks @ghoneycutt

**Comment by ghoneycutt** [comment]
Thanks everyone!

**Pull request closed without merging**
