### PR TITLE
Ruby 1.8 support

### PR DESCRIPTION
**Pull request by sathieu**
Ruby 1.8 doesn't support this hash syntax.

### CODE REVIEW

**Comment by alexjfisher** [comment]
@sathieu Ruby 1.8 hasn't been supported in Vox Pupuli maintained modules for a very long time now.

Puppet 3 support was also dropped at the beginning of the year when it became End Of Life.  Puppet 4 (and 5) ships with its own ruby, so even if you're using CentOS/Redhat 6 (which uses ruby 1.8 as its system ruby), you should be fine using this module.

**Comment by alexjfisher** [comment]
For further explanation of why ruby 1.8 isn't supported, please see https://github.com/voxpupuli/puppet-archive/issues/199 and https://github.com/voxpupuli/puppet-archive/issues/152

@sathieu Sorry if this isn't the response you were hoping for.  If you need help upgrading to puppet 4/5, please feel free to ask on the #voxpupuli IRC channel.  There are plenty of people there who would be more than happy to provide assistance.

**Comment by sathieu** [comment]
OK. this is not a surprise.

Note that my puppetmasters are with Puppet 4, but I have some old agents still alive. i.e, I need ruby1.8 support only client-side.

**Comment by alexjfisher** [comment]
IIRC I think it's actually more than just hash syntax in this module.  Something in https://github.com/voxpupuli/puppet-archive/commit/fc80536099e6ec471a79b64d4453212873be052d didn't work properly in ruby 1.8.  Can't remember what it was though!

**Comment by sathieu** [comment]
@alexjfisher Wasn't it 0ef5362f270ee308cf790e1c1878479e3466321b ? Because ''.to_sym raise "ArgumentError: interning empty string" on Ruby 1.8.

Would you merge my changes if I fix this too?

**Pull request closed without merging**
