### PR TITLE
voxpopuli/puppet-archive#142 Fix Cookie header double quotes on wget

### PR DESCRIPTION
**Pull request by randradas**
Fix surplus double quotes in Cookie header during wget params formatting.

### CODE REVIEW

**Comment by rnelson0** [comment]
@randradas You need to update the rspec test to match the new expectation. Once that is done I think this will be ready to merge. Thanks!

**Comment by randradas** [comment]
sure!, I will do it. Just need a bit of time to study spec test part. wget_spec.rb is the file, right?

**Comment by jyaworski** [comment]
Yes.

```rspec
Failures:

  1) Puppet::Type::Archive::ProviderWget#download cookie specified calls wget with default options and header containing cookie

     Failure/Error: wget(params)

     

       Archive[/tmp/example.zip](provider=wget) received :wget with unexpected arguments

         expected: (["http://home.lan/example.zip", "-O", String, "--max-redirect=5", "--header=\"Cookie: \"foo\""])

              got: (["http://home.lan/example.zip", "-O", "/tmp/example.zip", "--max-redirect=5", "--header=\"Cookie: foo\""])

       Diff:

       

       @@ -1,6 +1,6 @@

        [["http://home.lan/example.zip",

          "-O",

       -  String,

       +  "/tmp/example.zip",

          "--max-redirect=5",

       -  "--header=\"Cookie: \"foo\""]]

       +  "--header=\"Cookie: foo\""]]

       

     # ./lib/puppet/provider/archive/wget.rb:17:in `download'

     # ./spec/unit/puppet/provider/archive/wget_spec.rb:78:in `block (4 levels) in <top (required)>'
```

**Comment by randradas** [comment]
done guys, my first steps with bundle, rspec and ruby. do not hesitate to make any comment.

**Pull request merged**
