### PR TITLE
Cosmetic: adding the score and download badges from Puppet Forge

### PR DESCRIPTION
**Pull request by aerostitch**
Hi,

It is often nice to see that a module is really respectful of the Puppet standards and very used.
To show that without any effort, it's nice to use the score and download statistics badges so that people going to your main page see those data in a blink of an eye.

This commit adds them to the README.md

Thanks for the awesome work! ;)

Joseph

### CODE REVIEW

**Comment by aerostitch** [comment]
Tests are failing because of #117. Once this one is merged, we should be good on the tests.

**Comment by jyaworski** [comment]
Build status should be under voxpupuli and not puppet-community.

**Comment by aerostitch** [comment]
My bad, sorry, it was a bad merge. Fixed.

**Comment by aerostitch** [comment]
Rebased against the latest master for an easier merge. ;)

**Pull request merged**
