### PR TITLE
do not escape path on windows for unzip command

### LINKED ISSUE #343: Invalid pathname on Windows for names with invalid shell chars like '+'
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.10
- Ruby: 2.1.9p490
- Distribution: windows server 2012r2
- Module version: 3.0.0, 3.1.0

## How to reproduce (e.g Puppet code you use)
decompress an archive on windows server 2012r2 that contains a plus '+' sign in the name

## What are you seeing
File not found error.

## What behaviour did you expect instead
I expected the file to be extracted.

## Output log
unable to share log due to company policy

### PR DESCRIPTION
**Pull request by qs5779**
<!--
Thank you for contributing to this project!

#### Pull Request (PR) description

    Shellwords.shellescape does a bash style escape for invalid shell chars. On a windows pathname, it will inject invalid path char \ (which is a path separator on windows) into the path name being decompressed, which causes a failure in the decompress command. This change simply doesn't escape the

#### This Pull Request (PR) fixes the following issues

    Fixes #343

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @qs5779, thanks for opening up this PR. Can you please rebase after https://github.com/voxpupuli/puppet-archive/pull/345 got merged?

**Comment by qs5779** [comment]
rebased per request

**Comment by bastelfreak** [comment]
Hi @qs5779, can you take a look at the failing travis jobs? Please also have a look at the used email address in your commits. It isn't associated with your github account.

**Comment by qs5779** [comment]
I think I have my email address in all my global git configs, I have corrected of the faiing tests and working on the others, be patient please.

**Comment by bastelfreak** [comment]
Thanks for the work @qs5779 !

**Pull request merged**
