### PR TITLE
GH-55 use net::http to stream files

### PR DESCRIPTION
**Pull request by nanliu**
* Fix GH-55 large file memory issue.
* Remove puppet agent dependency on Faraday gem.
* make ruby default provider for windows.
* migrate functions away from faraday.
* change target release to 0.5.0

### CODE REVIEW

**Comment by nanliu** [comment]
WIP, I'm not sure level of effort to remove faraday from the existing functions and difficult to test without those services. Also still missing following features:

* follow http redirect
* http cookies

Need more testing for ruby provider handling of:
* proxy
* username/password

**Comment by nanliu** [comment]
@logicminds, would you be able interested to test this in your Windows environment and see if it resolves your issue so you don't need #118 anymore?

**Comment by jyaworski** [comment]
Are we just killing Faraday? Net::Http is likely better.

**Comment by nanliu** [comment]
Yeah, trying to remove the dependency since there was no way to fix #55 with faraday. The tricky part is dealing with the three functions https://github.com/voxpupuli/puppet-archive/blob/master/lib/puppet/parser/functions/artifactory_sha1.rb#L16-L22. Need some volunteers for testing those changes.

**Comment by dandunckelman** [comment]
I came up against this yesterday.  Impeccable timing.  If I get a chance, I'll see if I can help out.  Tied up right now.

**Comment by jyaworski** [comment]
I can actually test artifactory, but I need to see if it's been rolled out yet...

**Comment by nanliu** [comment]
@jyaworski I tested the new functions against jfrog's repo and added some spec tests. I couldn't find an example gocd md5 file and wrote it test based from memory. Anyhow, additional testing is appreciated.

**Comment by jyaworski** [comment]
@nanliu this doesn't appear to follow redirects, and it also looks like it's hardcoded to http in the art_url in the define.

```puppet
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: unexpected token at '<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx</center>
</body>
</html>
' at /etc/puppet/environments/archive_artifactory/modules/archive/manifests/artifactory.pp:38 on node domain.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

```puppet
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: unexpected token at '<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
' at /etc/puppet/environments/archive_artifactory/modules/archive/manifests/artifactory.pp
```

**Comment by jyaworski** [comment]
Following up from IRC, maybe we could drop the port parameter and pass a URI to be parsed. That way net::http can do its own thing.

**Comment by nanliu** [comment]
@jyaworski, both fixed, it should follow redirect for content, and use the correct url (instead of hard coded http in the manifest for checksum url).

**Comment by jyaworski** [comment]
That works. Maybe we should add more docs; it wasn't immediately clear that URL was the whole URL to the entire file.

Or maybe we should just deprecate port, and keep the base url (with :port/artifactory) and filepath separate like it is currently.

**Comment by nanliu** [comment]
I updated the docs significantly. After looking at archive::nexus, I can see how url as a parameter might be confusing. I didn't author nexus, so I have to dig around a bit to understand the parameters. If you have an alternate suggestion, let me know.

**Comment by jyaworski** [comment]
This LGTM now. I would say this is ready to be merged.

**Comment by jyaworski** [comment]
After looking over this, I'm willing to merge it now.

**Pull request merged**
